# Generated by Django 4.2.3 on 2023-07-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_seat_booked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='city',
            name='is_capital',
            field=models.BooleanField(default=False, verbose_name='Is Capital'),
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='country',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='country',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Timezone'),
        ),
    ]
