# Generated by Django 4.2.3 on 2023-07-25 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_trainschedule_arrival_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название станции')),
                ('station_type', models.CharField(blank=True, choices=[('type_1', 'Тип станции 1'), ('type_2', 'Тип станции 2'), ('type_3', 'Тип станции 3')], default='type_1', max_length=10, null=True, verbose_name='Тип станции')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_stations', to='core.country', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Железнодорожная станция',
                'verbose_name_plural': 'Железнодорожные станции',
            },
        ),
    ]
