# Generated by Django 4.2.3 on 2023-07-25 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_trainstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainstation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_stations', to='core.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='trainstation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='trainstation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True, verbose_name='Долгота'),
        ),
    ]
